# Base configuration
# Keys without a value are passed into the config via a .env file in the same
# directory as the `docker-compose` command was run from
version: "2"
services:
  app:
    image: octri.ohsu.edu/jarrunner8:2019q2
    ports:
      - 8080:8080
    volumes:
      - ./target/hpoOnFhir.jar:/app.jar
    environment:
      - SERVER_SERVLET_CONTEXTPATH
      - FHIR_SERVER_NAME
      - FHIR_SERVER_URL
      - FHIR_SERVER_VERSION
      - FHIR_SERVER_AUTHORIZE
      - FHIR_SERVER_TOKEN
      - FHIR_SERVER_REDIRECT
      - FHIR_SERVER_CLIENT_ID
      - FHIR_SERVER_CLIENT_SECRET
      - FHIR_SERVER_LOGGING