# Base configuration
# Keys without a value are passed into the config via a .env file in the same
# directory as the `docker-compose` command was run from
version: "2"
services:
  app:
    image: octri.ohsu.edu/jarrunner:2018q4
    volumes:
      - ./target/hpoOnFhir.jar:/app.jar
    environment:
      - SERVER_SERVLET_CONTEXTPATH
      - CLIENT_SECRET
